"""Curated official product references for the Ecuador MVP.

Prices and stock belong to each retailer and can change. These records provide
fallback references when a live catalog refresh is unavailable.
"""

VERIFIED_AT = "2026-06-22"

RETAILERS = [
    ("dermasoft", "Dermasoft Ecuador", "https://dermasoft.com.ec/"),
    ("gloria-saltos", "Gloria Saltos", "https://www.gloriasaltos.com/"),
    ("dipaso", "Dipaso", "https://www.dipaso.com.ec/"),
    ("mendieta", "Mendieta Beauty", "https://mendietabeauty.com/"),
    ("fybeca", "Fybeca", "https://www.fybeca.com/dermocosmetica/cuidado-especializado-del-rostro/"),
]

PRODUCTS = [
    # id, retailer, name, brand, category, step, price, url, skin types, concerns, ingredients, usage, stock
    ("dermasoft-cerave-air-foam", "dermasoft", "Limpiador Air Foam Reequilibrante", "CeraVe", "cleanser", "cleanse", 21.73, "https://dermasoft.com.ec/producto/cerave-limpiador-air-foam-reequilibrante/", ["Grasa", "Mixta", "Mixta deshidratada"], ["oil-balance", "pores", "gentle-care"], ["ceramidas", "aminoácidos"], "Usar mañana y noche sobre el rostro húmedo.", True),
    ("dermasoft-martiderm-micellar", "dermasoft", "Solución Micelar Limpiadora 3 en 1", "MartiDerm", "cleanser", "cleanse", 27.37, "https://dermasoft.com.ec/producto/martiderm-essentials-solucion-micelar-limpiadora-3-en-1/", ["Seca", "Sensible", "Equilibrada"], ["gentle-care", "hydration"], ["micelas"], "Usar para limpieza suave y retirar sin fricción.", True),
    ("dermasoft-queratol-ceramidas", "dermasoft", "Crema Hidratante Ceramidas Piel Sensible", "Queratol", "moisturizer", "moisturize", 17.09, "https://dermasoft.com.ec/producto/queratol-ceramidas-crema-hidratante-piel-sensible/", ["Seca", "Sensible", "Mixta deshidratada"], ["hydration", "gentle-care", "fine-lines"], ["ceramidas"], "Aplicar después de limpiar, mañana y noche.", True),
    ("dermasoft-resvenova-fluido", "dermasoft", "Fluido Ultrahidratante Resvenova", "Novaderma", "moisturizer", "moisturize", 52.83, "https://dermasoft.com.ec/producto/novaderma-resvenova-fluido-ultrahidratante/", ["Equilibrada", "Seca", "Mixta deshidratada"], ["hydration", "texture", "fine-lines"], ["ingredientes hidratantes"], "Aplicar una capa fina después de limpiar.", True),
    ("dermasoft-solarsafe-gel", "dermasoft", "Protector Solarsafe Gel Toque Seco", "Novaderma", "sunscreen", "protect", 29.33, "https://dermasoft.com.ec/producto/novaderma-protector-solarsafe-gel-toque-seco/", ["Grasa", "Mixta", "Equilibrada"], ["sun-protection", "oil-balance", "tone"], ["filtros UV"], "Último paso de la mañana; reaplicar según exposición.", True),
    ("mendieta-centella-foam", "mendieta", "Centella Cleansing Foam", "Mixsoon", "cleanser", "cleanse", 25.00, "https://mendietabeauty.com/product/mixsoon-centella-cleansing-foam-espuma-limpiadora-calmante-para-piel-mixta-grasa-y-sensible/", ["Mixta", "Grasa", "Sensible"], ["gentle-care", "oil-balance", "redness"], ["centella asiática"], "Usar sobre piel húmeda y enjuagar.", True),
    ("mendieta-bean-oil", "mendieta", "Bean Cleansing Oil", "Mixsoon", "cleanser", "cleanse", 30.00, "https://mendietabeauty.com/product/mixsoon-bean-cleansing-oil-aceite-limpiador-de-frijoles/", ["Seca", "Equilibrada", "Mixta deshidratada"], ["gentle-care", "hydration"], ["aceite de soja", "extracto de frijol"], "Masajear sobre piel seca y emulsionar con agua.", True),
    ("mendieta-bean-cream", "mendieta", "Bean Cream", "Mixsoon", "moisturizer", "moisturize", 42.95, "https://mendietabeauty.com/product/mixsoon-bean-cream-crema-hidratante-nutritiva-de-frijoles-50ml/", ["Seca", "Equilibrada", "Mixta deshidratada"], ["hydration", "texture"], ["extracto de frijol"], "Aplicar una capa fina después del tratamiento.", True),
    ("mendieta-joseon-sunstick", "mendieta", "Matte Sun Stick Mugwort + Camelia SPF50+", "Beauty of Joseon", "sunscreen", "protect", 27.00, "https://mendietabeauty.com/product/barra-solar-mate-beauty-of-joseon-matte-sun/", ["Grasa", "Mixta", "Equilibrada"], ["sun-protection", "oil-balance"], ["artemisia", "camelia", "filtros UV"], "Aplicar en cantidad suficiente y reaplicar; confirmar cobertura en la ficha.", True),
    ("dipaso-centella-cleanser", "dipaso", "Madagascar Centella Espuma Limpiadora 125 ml", "SKIN1004", "cleanser", "cleanse", 23.04, "https://www.dipaso.com.ec/madagascar-centella-espuma-limpiadora-125ml---skin1004-1/p", ["Mixta", "Grasa", "Sensible"], ["gentle-care", "oil-balance"], ["centella asiática"], "Usar mañana y noche y enjuagar.", True),
    ("dipaso-cerave-cleanser", "dipaso", "Gel Limpiador Espumoso", "CeraVe", "cleanser", "cleanse", 25.31, "https://www.dipaso.com.ec/gel-limpiador-espumoso---cerave/p", ["Grasa", "Mixta", "Equilibrada"], ["gentle-care", "oil-balance", "pores"], ["ceramidas", "niacinamida"], "Usar mañana y noche y enjuagar.", True),
    ("dipaso-bean-cream", "dipaso", "Bean Cream Crema Hidratante 50 ml", "Mixsoon", "moisturizer", "moisturize", 36.43, "https://www.dipaso.com.ec/bean-cream-crema-hidratante-sin-sensacion-grasosa-50-ml---mixsoon/p", ["Seca", "Equilibrada", "Mixta deshidratada"], ["hydration", "texture"], ["extracto de frijol"], "Aplicar después de limpiar.", True),
    ("dipaso-revox-spf", "dipaso", "Protector Solar Just SPF 50+ Piel Grasa 30 ml", "Revox", "sunscreen", "protect", 9.35, "https://www.dipaso.com.ec/protector-solar-just-spf-50-piel-grasa-30ml---revox/p", ["Grasa", "Mixta"], ["sun-protection", "oil-balance", "tone"], ["filtros UV"], "Último paso de la mañana; reaplicar.", True),
    ("dipaso-nivea-spf", "dipaso", "Protector Solar Sun Shine FPS50", "Nivea", "sunscreen", "protect", 15.64, "https://www.dipaso.com.ec/protector-solar-sun-shine-fps50-nivea/p", ["Equilibrada", "Seca", "Mixta deshidratada"], ["sun-protection", "tone"], ["filtros UV"], "Último paso de la mañana; reaplicar.", True),
    ("dipaso-niacinamide-toner", "dipaso", "Tónico Facial Niacinamida 200 ml", "Revuele", "treatment", "treat", 8.69, "https://www.dipaso.com.ec/tonico-facial-niacinamida-200ml-revuele/p", ["Grasa", "Mixta"], ["oil-balance", "pores", "tone"], ["niacinamida"], "Introducir una vez al día y suspender si irrita.", True),
    ("gloria-roundlab-cleanser", "gloria-saltos", "Jabón Facial Birch Juice", "Round Lab", "cleanser", "cleanse", 17.00, "https://www.gloriasaltos.com/producto/jabon-facial-todo-tipo-de-piel-birch-juice-moisturizin-cleanse-round-lab/", ["Seca", "Grasa", "Mixta", "Equilibrada", "Sensible", "Mixta deshidratada"], ["gentle-care", "hydration"], ["savia de abedul"], "Usar sobre piel húmeda y enjuagar.", True),
    ("gloria-mixsoon-bean", "gloria-saltos", "Bean Cream", "Mixsoon", "moisturizer", "moisturize", 41.00, "https://www.gloriasaltos.com/producto/crema-hidratante-bean-cream-mixsoon/", ["Seca", "Mixta", "Equilibrada", "Mixta deshidratada"], ["hydration", "texture"], ["extracto de frijol"], "Aplicar mañana o noche.", True),
    ("gloria-revitalift-gel", "gloria-saltos", "Crema Gel Facial Revitalift Ácido Hialurónico", "L'Oréal", "moisturizer", "moisturize", 24.75, "https://www.gloriasaltos.com/producto/crema-gel-facial-hidratante-rellenador-de-dia-piel-mixta-a-grasa-revitalift-acido-hialuronico-loreal/", ["Grasa", "Mixta"], ["hydration", "texture", "fine-lines"], ["ácido hialurónico"], "Aplicar una capa fina después del tratamiento.", True),
    ("gloria-roundlab-serum", "gloria-saltos", "Sérum Facial Birch Juice", "Round Lab", "treatment", "treat", 25.00, "https://www.gloriasaltos.com/producto/serum-facial-piel-seca-y-sensible-birch-juice-round-lab/", ["Seca", "Sensible", "Mixta deshidratada"], ["hydration", "redness"], ["savia de abedul"], "Aplicar antes de la hidratante.", True),
    ("gloria-roundlab-spf", "gloria-saltos", "Birch Juice Moisturizing Sunscreen SPF50+", "Round Lab", "sunscreen", "protect", 24.00, "https://www.gloriasaltos.com/producto/bloqueador-solar-facial-birch-juice-moisturizin-sunscreen-spf-50-pa-round-lab/", ["Grasa", "Mixta", "Sensible", "Equilibrada"], ["sun-protection", "hydration", "tone"], ["savia de abedul", "filtros UV"], "Último paso de la mañana; reaplicar.", True),
    ("fybeca-cerave-foam", "fybeca", "Gel Limpiador Espumoso 236 ml", "CeraVe", "cleanser", "cleanse", 19.80, "https://www.fybeca.com/gel-limpiador-espumoso-piel-normal-a-grasa-236-ml-unidad/ECFY_100280139.html", ["Grasa", "Mixta", "Equilibrada"], ["oil-balance", "pores", "gentle-care"], ["ceramidas", "ácido hialurónico", "niacinamida"], "Usar mañana y noche y enjuagar.", True),
    ("fybeca-cerave-dry", "fybeca", "Crema Hidratante Piel Seca a Muy Seca 177 ml", "CeraVe", "moisturizer", "moisturize", None, "https://www.fybeca.com/crema-hidratante-piel-seca-a-muy-seca-177-ml/ECFY_404631.html", ["Seca", "Sensible", "Mixta deshidratada"], ["hydration", "gentle-care", "fine-lines"], ["ceramidas", "ácido hialurónico"], "Aplicar después de limpiar.", None),
    ("fybeca-ceramide-spf30", "fybeca", "Crema Facial Ceramide SPF30 50 ml", "Revox", "moisturizer", "moisturize", 15.52, "https://www.fybeca.com/ceramide-crema-facial-hidratante-spf30-50ml/ECFY_549421.html", ["Grasa", "Mixta", "Equilibrada"], ["hydration", "oil-balance", "gentle-care"], ["ceramidas", "niacinamida"], "Aplicar como hidratante; usar además protección solar suficiente.", True),
    ("fybeca-umbrella-gel", "fybeca", "Protector Solar Umbrella Gel SPF 50", "Umbrella", "sunscreen", "protect", None, "https://www.fybeca.com/protector-solar-umbrella-gel-spf-50-60-g-caja/ECFY_172883.html", ["Grasa", "Mixta", "Equilibrada"], ["sun-protection", "oil-balance", "tone"], ["filtros UV"], "Último paso de la mañana; reaplicar.", None),
    ("fybeca-clinique-mineral", "fybeca", "Protector Solar Mineral SPF 50 30 ml", "Clinique", "sunscreen", "protect", 50.20, "https://www.fybeca.com/clinique-protector-solar-mineral-50-spf-30-ml/ECFY_571427.html", ["Seca", "Sensible", "Equilibrada", "Mixta deshidratada"], ["sun-protection", "tone", "gentle-care"], ["óxido de zinc", "dióxido de titanio", "glicerina"], "Último paso de la mañana; reaplicar.", True),
    ("fybeca-isdin-sensitive", "fybeca", "Crema Facial Hidratante Piel Sensible 50 ml", "ISDIN", "moisturizer", "moisturize", 37.27, "https://www.fybeca.com/crema-facial-hidratante-para-piel-sensible-50ml/ECFY_565924.html", ["Sensible", "Seca"], ["hydration", "gentle-care", "redness"], ["ingredientes hidratantes"], "Aplicar después de limpiar.", False),
]
